Hw 1
dsemenovkib/sta-with-python-2021 pull request #1
Opened 2021-03-23 17:37 UTC by dsemenovkib

2021-03-23 18:58 UTC, zhidelev requested changes

2021-03-23 18:58 UTC, zhidelev commented on Lecture_1_Introduction_homework/test_sample.py
> +    return ''.join(test_string.split())
Привет, да, эти варианты работают, но можно использовать метод ```strip()``` - тесты тоже проходят, а запись лаконичней. Поменяй, пожалуйста,  на ```strip()``` и ДЗ сдано 😃

2021-03-23 20:55 UTC, dsemenovkib commented on Lecture_1_Introduction_homework/test_sample.py
> +    return ''.join(test_string.split())
привет, да, strip() тоже рассматривал, и да, тесты пройдут на этих данных, но если пробелы или табуляции будут в центре - то не пройдут. И я смотрел пристально на описание метода, которое выглядит как """Removes spaces, tabs for the string""", а не """Removes leading and trailing spaces, tabs for the string""", именно поэтому сознательно не был выбран strip(), хотя действительно, было бы лаконичнее
Поменять мне не сложно, но так было сделано намеренно, в соответствии с описанием метода

2021-03-24 07:29 UTC, zhidelev commented on Lecture_1_Introduction_homework/test_sample.py
> +    return ''.join(test_string.split())
Тоже верно 👍 . Хорошо, давай тогда оставим так, если ты рассматривал ```strip()```, то подумал о разных вариантах. Я расширю количество тестов для следующих групп, чтобы было меньше неопределённостей.

2021-03-24 07:29 UTC, zhidelev approved these changes

2021-04-07 06:01 UTC, merged